name: Deploy
on:
  push:
    branches: 
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup RapidFort Catalog
        uses: rapidfort/setup-rfcatalog@v1  # Changed from v2 to v1
        with:
          access-id: ${{ secrets.RF_ACCESS_ID }}
          secret: ${{ secrets.RF_SECRET_ACCESS_KEY }}
          
      - name: Test rfcatalog
        env:
          RF_CONTAINER_ENGINE: docker
        run: |
          echo "Testing rfcatalog installation..."
          rfcatalog --version
          
          # Test generating datasource
          echo "Generating test datasource..."
          rfcatalog -r alpine -f renovate | jq .